#!/usr/bin/python
import json
import argparse

DATA = {"latitude": 81.191900, "longitude": 114.514810, "altitude": 1.1, "accuracy": 45.1,
        "vertical_accuracy": 4.1, "bearing": 1.4, "speed": 5.1, "elapsedMs": 41, "provider": "810fucker"}


def main():
    global DATA
    parser = argparse.ArgumentParser(
        prog="termux-location", description="Get the device location.")
    parser.add_argument('-p', metavar='provider',
                        help='location provider [gps/network/passive] (default: gps)')
    parser.add_argument('-r', metavar='request',
                        help='kind of request to make [once/last/updates] (default: once)')
    args = parser.parse_args()
    return json.dumps(DATA, indent=2)


if __name__ == '__main__':
    print(main())
